using Mutagen.Bethesda;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace SynOppositeGenderAnimsTweak
{
    public class Program
    {
        public static Lazy<Settings> PatchSettings = null!;
        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings("Settings", "settings.json", out PatchSettings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "SynOppositeGenderAnimsTweak.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            // set local vars
            bool isOnlyUnique = PatchSettings.Value.IsOnlyUnique;
            var oppositeGenderAnimsFlag = NpcConfiguration.Flag.OppositeGenderAnims;
            var uniqueFlag = NpcConfiguration.Flag.Unique;

            foreach (var npcGetter in state.LoadOrder.PriorityOrder.Npc().WinningOverrides())
            {
                // skip invalid npcs
                if (npcGetter == null) continue;
                if (!npcGetter.Configuration.Flags.HasFlag(oppositeGenderAnimsFlag)) continue;
                if (isOnlyUnique && !npcGetter.Configuration.Flags.HasFlag(uniqueFlag)) continue;

                Console.WriteLine($"Remove opposite gender flag for '{npcGetter.FormKey.ID}|{npcGetter.EditorID}'");
                state.PatchMod.Npcs.GetOrAddAsOverride(npcGetter).Configuration.Flags &= ~oppositeGenderAnimsFlag;
            }
        }
    }
}
